# -*- mode: ruby -*-
# vi: set ft=ruby :
 
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.define "node1" do |node1|
     node1.vm.box = "ubuntu/focal64"
     node1.vm.hostname = "node1"
     node1.vbguest.auto_update = false
     node1.vm.network "private_network", ip: "192.168.60.11"
     node1.vm.provision "shell", inline: <<-SHELL
       sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
       service ssh restart
     SHELL
    end
        # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.define "node2" do |node2|
     node2.vm.box = "ubuntu/focal64"
     node2.vm.hostname = "node2"
     node2.vbguest.auto_update = false
     node2.vm.network "private_network", ip: "192.168.60.12"
     node2.vm.provision "shell", inline: <<-SHELL
       sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
       service ssh restart
     SHELL
    end
      # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.define "node3" do |node3|
     node3.vm.box = "ubuntu/focal64"
     node3.vm.hostname = "node3"
     node3.vbguest.auto_update = false
     node3.vm.network "private_network", ip: "192.168.60.13"
     node3.vm.provision "shell", inline: <<-SHELL
       sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/#g' /etc/ssh/sshd_config
       service ssh restart
     SHELL
    end
   end